# Generated by Django 5.2.4 on 2025-07-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_remove_student_roll_number_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-28 00:00:00'),
            preserve_default=False,
        ),
    ]
