# Generated by Django 5.2.4 on 2025-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_attendance_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('technical', 'technical'), ('sports', 'sports')], default='2025-07-28 00:00:00', max_length=20),
            preserve_default=False,
        ),
    ]
