# Generated by Django 5.2.4 on 2025-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('sports', 'Sports')], max_length=20),
        ),
    ]
