# Generated by Django 5.2.4 on 2025-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('tech_events', 'Technical'), ('sport_events', 'Sports')], max_length=20),
        ),
    ]
