# Generated by Django 5.2.4 on 2025-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Sports', 'Sports')], max_length=20),
        ),
    ]
