# Generated by Django 5.2.4 on 2025-07-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0007_alter_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nName', models.CharField(max_length=100)),
                ('nDescription', models.TextField()),
                ('nDate', models.DateField()),
                ('nTime', models.TimeField()),
                ('updatedBy', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('exam', 'Exam'), ('event', 'Event'), ('holiday', 'Holiday'), ('circular', 'Circular'), ('placement', 'Placement'), ('general', 'General')], default='general', max_length=20)),
            ],
        ),
    ]
