# Generated by Django 5.2.4 on 2025-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0008_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50)),
                ('ndescribe', models.TextField()),
                ('ndate', models.DateField()),
                ('ntime', models.TimeField()),
                ('updatedby', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='notes/')),
                ('sub', models.CharField(max_length=20)),
            ],
        ),
    ]
