# Generated by Django 5.2.4 on 2025-08-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0009_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assin', models.CharField(max_length=50)),
                ('adescribe', models.TextField()),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
                ('aupdatedby', models.CharField(max_length=50)),
                ('afile', models.FileField(upload_to='notes/')),
                ('asub', models.CharField(max_length=20)),
            ],
        ),
    ]
