# Generated by Django 5.2.4 on 2025-08-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0012_user_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
